name: automationstore.com e2e tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Allure Reporter
        run: npm install -g allure-commandline

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build --if-present

      - name: Run tests and generate Allure report
        run: npm run autostore

      - name: Archive Allure reports
        run: |
          tar -czf allure-reports.tar.gz allure-report allure-results

      - name: Upload Allure report archive as artifact
        uses: actions/upload-artifact@v2
        with:
          name: allure-reports-archive
          path: allure-reports.tar.gz

      - name: Upload Archive to Database
        run: |
          ./utils/db_connect.js downloaded-artifacts/allure-reports.tar.gz
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
