name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Allure Reporter
        run: npm install -g allure-commandline

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build --if-present

      - name: Run tests and generate Allure report
        run: |
          npm run autostore
          allure generate allure-results --clean
        continue-on-error: true

      - name: Archive Allure report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report/
